parameters:
    hgabka_kunstmaan_settings.settings_manager.class: 'Hgabka\KunstmaanSettingsBundle\Helper\SettingsManager'

services:
    hgabka_kunstmaan_settings.menu.adaptor.settings:
        class: Hgabka\KunstmaanSettingsBundle\Helper\Menu\SettingsMenuAdaptor
        arguments: ['@security.authorization_checker']
        tags:
            -  { name: kunstmaan_admin.menu.adaptor }

    hgabka_kunstmaan_settings.settings_manager:
        class: '%hgabka_kunstmaan_settings.settings_manager.class%'
        arguments: ["@doctrine", "%kernel.cache_dir%"]

    hgabka_kunstmaan_settings.settings_type:
        class: Hgabka\KunstmaanSettingsBundle\Form\SettingAdminType
        arguments: ["@security.authorization_checker", '@hgabka_kunstmaan_settings.settings_manager']
        tags:
            - { name: form.type }

    hgabka_kunstmaan_settings.settings_twig_extension:
        class: Hgabka\KunstmaanSettingsBundle\Twig\HgabkaKunstmaanSettingsTwigExtension
        arguments: ['@hgabka_kunstmaan_settings.settings_manager']
        public: false
        tags:
            - { name: twig.extension }

    hgabka_kunstmaan_settings.validator.setting:
        class: Hgabka\KunstmaanSettingsBundle\Validator\SettingValidator
        arguments: ['@hgabka_kunstmaan_settings.settings_manager']
        tags:
            - { name: validator.constraint_validator }

    hgabka_kunstmaan_settings.setting_subscriber:
        class: Hgabka\KunstmaanSettingsBundle\EventListener\SettingSubscriber
        arguments: ['@hgabka_kunstmaan_settings.settings_manager']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

