parameters:
    hgabka_kunstmaan_settings.settings_manager.class: 'Hgabka\KunstmaanSettingsBundle\Helper\SettingsManager'

services:
    hgabka_kunstmaan_settings.settings_manager:
        class: '%hgabka_kunstmaan_settings.settings_manager.class%'
        arguments: ['@doctrine']

    hgabka_kunstmaan_settings.settings_twig_extension:
        class: Hgabka\KunstmaanSettingsBundle\Twig\HgabkaKunstmaanSettingsTwigExtension
        arguments: ['@hgabka_kunstmaan_settings.settings_manager']
        public: false
        tags:
            - { name: twig.extension }


